name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Makefiles
      working-directory: ${{github.workspace}}/cpp
      run:|
        set(ENV{CC} "gcc" )
        set(ENV{CXX} "g++")
        cmake -G "Unix Makefiles" -S . -B build

    - name: Build
      working-directory: ${{github.workspace}}/cpp
      shell: bash
      run:|
        set(ENV{CC} "gcc" )
        set(ENV{CXX} "g++")
        cmake --build ./build

    - name: Test
      working-directory: ${{github.workspace}}/cpp/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
